### ISSUE TITLE
Activate the shield for a moment after destroying a core

### ISSUE THREAD

**Issue by olofson** [olofson/koboredux#168]
For some more opportunities to fly into bases for aggressive attacks, we could activate the shield (invincibility; originally implemented for #164) for a moment after the core is destroyed, so the player has a greater chances of making it out alive.

The logic is that the shield is activated automatically as the ship absorbs energy from the destroyed core; the same mechanism that currently charges the ship's shields as a core is destroyed.

**Comment by Chaiavi** [comment]
I vote for the momentary shield, it is a good idea

**Comment by olofson** [comment]
Yeah, it crossed my mind that this is a lot like the "glory kill" mechanic in Doom, where it works brilliantly! In Kobo, destroying a base and literally flying right on through it, is one of those rewarding game play moments, and it makes sense to build further on that.

**Comment by Chaiavi** [comment]
Especially on bases where you need to enter a maze of tubes in order to
destroy the core (like in star wars when destroying the death star?), that
will be a suicide mission which is a bummer, unless ... this feature is
implemented :-)
