### ISSUE TITLE
How to play the GPL data/release?

### ISSUE THREAD

**Issue by qubodup** [olofson/koboredux#324]
Hello,

I am one of the backers and received the proprieatary release via itch.

How can I play the GPL dataset though? I couldn't figure out how to do it by moving files around from this git repo to the gfx/sfx folders in the release. Is there a way?

Unfortunately I couldn't figure out how to build on linux (and I am extremely underexperienced with compiling on windows).

Thanks!

**Comment by olofson** [comment]
The game uses themes for graphics and sound, and these can be selected using the -gfxtheme and -sfxtheme switches/config options respectively. So, you can start the game from the command line like this:
```
kobord.exe -gfxtheme mono -sfxtheme chip
```
To switch back:
```
kobord.exe -gfxtheme redux -sfxtheme redux
```
If the game is started like this, and then closed via the GUI menu, the theme selection is save in the configuration file.

Alternatively, you can edit the respective keys in koboredux.cfg. (The keys there have the same names as the respective command line switches.)

There's also a third option: The game will fall back to the GPL themes if the Redux themes are not found, so one way is to just move or rename the 'redux' folders in 'sfx' and 'gfx' respectively. (Themes are located by folder name.)

There will be a GUI for this soon; see #295. Unfortunately, I decided it was't important enough for the first release. :-)


As to building, I realize I haven't even mentioned that in the README. Need to fix that. :-)

You can have a look at the sound engine, (Audiality 2)[https://github.com/olofson/audiality2] for now, as it has a nearly identical build system, and you'll need to install that first anyway.

**Comment by olofson** [comment]
Build instructions added, and theme selector implemented, so I'm closing this. :-)
