### ISSUE TITLE
INSTALL.md file calls to the wrong configuration script

### ISSUE THREAD

**Issue by realkhaxan** [olofson/koboredux#470]
Things to modify/consider to modify in INSTALL.md

_Git Protocol_
Maybe add the option to git clone via git/https in addition to the git/ssh protocol? (to save the trouble with the public key)

_Configure Script_
References to ./cfg-all should be made to **./configure** instead
Also, indicate that the configure script could optionally take a build parameter, either demo or release.

_Make_
Change to the desired build directory and do "sudo make" and "sudo make install"
or... 
sudo ./make-all 
Change to the build directory and "sudo make install"

**Comment by olofson** [comment]
Yep, totally forgot to update that after refactoring the build scripts! Thanks, and sorry about the confusion. :-)

**Comment by realkhaxan** [comment]
Awesome! **Thank you** :)
